// MemberAccountManager ABI
// Exported as a const for wagmi/viem use

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const memberAccountManagerAbi = [
  {
    inputs: [{ internalType: "address", name: "caller", type: "address" }],
    name: "addAuthorizedCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "caller", type: "address" }],
    name: "AuthorizedCallerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "caller", type: "address" }],
    name: "AuthorizedCallerRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint256", name: "potId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cycleId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "bidAmount", type: "uint256" },
      { indexed: false, internalType: "bool", name: "didBid", type: "bool" },
    ],
    name: "BidUpdated",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
      { internalType: "uint256", name: "cycleId", type: "uint256" },
    ],
    name: "markAsWinner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "user", type: "address" }],
    name: "MemberRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint256", name: "potId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cycleId", type: "uint256" },
    ],
    name: "ParticipationUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint256", name: "potId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cycleId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "PotFundingUpdated",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "registerMember",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "caller", type: "address" }],
    name: "removeAuthorizedCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
      { internalType: "uint256", name: "cycleId", type: "uint256" },
      { internalType: "uint256", name: "bidAmount", type: "uint256" },
      { internalType: "bool", name: "didBid", type: "bool" },
    ],
    name: "updateBidInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
      { internalType: "uint256", name: "cycleId", type: "uint256" },
      { internalType: "uint256", name: "contribution", type: "uint256" },
      { internalType: "bool", name: "isCreator", type: "bool" },
    ],
    name: "updateParticipation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
      { internalType: "uint256", name: "cycleId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "updatePotFundingDetails",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint256", name: "potId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cycleId", type: "uint256" },
    ],
    name: "WinnerMarked",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "authorizedCallers",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
      { internalType: "uint256", name: "cycleId", type: "uint256" },
    ],
    name: "getCycleParticipation",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "cycleId", type: "uint256" },
          { internalType: "uint256", name: "contribution", type: "uint256" },
          { internalType: "uint256", name: "bidAmount", type: "uint256" },
          { internalType: "bool", name: "didBid", type: "bool" },
          { internalType: "bool", name: "won", type: "bool" },
        ],
        internalType: "struct MemberAccountManager.CycleParticipation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "getMemberByIndex",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getMemberProfile",
    outputs: [
      { internalType: "bool", name: "registered", type: "bool" },
      { internalType: "uint256", name: "totalCyclesParticipated", type: "uint256" },
      { internalType: "uint256", name: "totalCyclesWon", type: "uint256" },
      { internalType: "uint256", name: "totalContribution", type: "uint256" },
      { internalType: "uint256", name: "reputationScore", type: "uint256" },
      { internalType: "uint256", name: "lastJoinedTimestamp", type: "uint256" },
      { internalType: "uint256[]", name: "createdPots", type: "uint256[]" },
      { internalType: "uint256[]", name: "joinedPots", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "potId", type: "uint256" },
    ],
    name: "getPotCycles",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getReputationScore",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getTotalMembers", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getWinRate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "isRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
] as const;

export const MEMBER_MANAGER_ADDRESS = process.env.NEXT_PUBLIC_MEMBER_MANAGER_ADDRESS as `0x${string}` | undefined;